/** Album team order (photo index 3–50), Mexico → Panama */
export const TEAMS = [
  { photoIndex: 3, name: "Mexico", code: "MEX", group: "A" },
  { photoIndex: 4, name: "South Africa", code: "RSA", group: "A" },
  { photoIndex: 5, name: "Korea Republic", code: "KOR", group: "A" },
  { photoIndex: 6, name: "Czechia", code: "CZE", group: "A" },
  { photoIndex: 7, name: "Canada", code: "CAN", group: "B" },
  { photoIndex: 8, name: "Bosnia-Herzegovina", code: "BIH", group: "B" },
  { photoIndex: 9, name: "Qatar", code: "QAT", group: "B" },
  { photoIndex: 10, name: "Switzerland", code: "SUI", group: "B" },
  { photoIndex: 11, name: "Brazil", code: "BRA", group: "C" },
  { photoIndex: 12, name: "Morocco", code: "MAR", group: "C" },
  { photoIndex: 13, name: "Haiti", code: "HAI", group: "C" },
  { photoIndex: 14, name: "Scotland", code: "SCO", group: "C" },
  { photoIndex: 15, name: "USA", code: "USA", group: "D" },
  { photoIndex: 16, name: "Paraguay", code: "PAR", group: "D" },
  { photoIndex: 17, name: "Australia", code: "AUS", group: "D" },
  { photoIndex: 18, name: "Türkiye", code: "TUR", group: "D" },
  { photoIndex: 19, name: "Germany", code: "GER", group: "E" },
  { photoIndex: 20, name: "Curaçao", code: "CUW", group: "E" },
  { photoIndex: 21, name: "Côte d'Ivoire", code: "CIV", group: "E" },
  { photoIndex: 22, name: "Ecuador", code: "ECU", group: "E" },
  { photoIndex: 23, name: "Netherlands", code: "NED", group: "F" },
  { photoIndex: 24, name: "Japan", code: "JPN", group: "F" },
  { photoIndex: 25, name: "Sweden", code: "SWE", group: "F" },
  { photoIndex: 26, name: "Tunisia", code: "TUN", group: "F" },
  { photoIndex: 27, name: "Belgium", code: "BEL", group: "G" },
  { photoIndex: 28, name: "Egypt", code: "EGY", group: "G" },
  { photoIndex: 29, name: "Iran", code: "IRN", group: "G" },
  { photoIndex: 30, name: "New Zealand", code: "NZL", group: "G" },
  { photoIndex: 31, name: "Spain", code: "ESP", group: "H" },
  { photoIndex: 32, name: "Cabo Verde", code: "CPV", group: "H" },
  { photoIndex: 33, name: "Saudi Arabia", code: "KSA", group: "H" },
  { photoIndex: 34, name: "Uruguay", code: "URU", group: "H" },
  { photoIndex: 35, name: "France", code: "FRA", group: "I" },
  { photoIndex: 36, name: "Senegal", code: "SEN", group: "I" },
  { photoIndex: 37, name: "Iraq", code: "IRQ", group: "I" },
  { photoIndex: 38, name: "Norway", code: "NOR", group: "I" },
  { photoIndex: 39, name: "Argentina", code: "ARG", group: "J" },
  { photoIndex: 40, name: "Algeria", code: "ALG", group: "J" },
  { photoIndex: 41, name: "Austria", code: "AUT", group: "J" },
  { photoIndex: 42, name: "Jordan", code: "JOR", group: "J" },
  { photoIndex: 43, name: "Portugal", code: "POR", group: "K" },
  { photoIndex: 44, name: "Congo DR", code: "COD", group: "K" },
  { photoIndex: 45, name: "Uzbekistan", code: "UZB", group: "K" },
  { photoIndex: 46, name: "Colombia", code: "COL", group: "K" },
  { photoIndex: 47, name: "England", code: "ENG", group: "L" },
  { photoIndex: 48, name: "Croatia", code: "CRO", group: "L" },
  { photoIndex: 49, name: "Ghana", code: "GHA", group: "L" },
  { photoIndex: 50, name: "Panama", code: "PAN", group: "L" },
] as const;

export const ALBUM_PHOTOS_DIR =
  "album-pgs/drive-download-20260528T223837Z-3-001";
